site_name: ATCO Katapult Fielding Manual

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - md_in_html

nav:
  - Manual: index.md
