site_name: ATCO Katapult Fielding Manual

theme:
  name: material
  features:
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2-4
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

nav:
  - Manual: index.md
