site_name: Fielding Manual

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - toc.integrate

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - md_in_html

nav:
  - Manual: index.md
